"""empty message

Revision ID: 0882f1a638d3
Revises: e31b8acb9b23
Create Date: 2024-10-27 21:14:10.016353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0882f1a638d3'
down_revision = 'e31b8acb9b23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'recurring_transaction', ['recurring_transaction_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'transaction', ['recurring_transaction_id'], ['id'])

    # ### end Alembic commands ###
